### ISSUE TITLE
Query design

### ISSUE THREAD

**Issue by bb00le** [OSS-Java-Seminar-2022/BRK-Car-Sharing#18]
Design queries for mongo db.

Query Vehicle collection by distance from user:

- method receives user coordinates, distance in meters and returns list of vehicle objects in that range
----------------------------------------------------------------------------------------------------------------

Query Trip collection by date range:

- method receives dateFrom and dateTo, returns list of trip object in that range
--------------------------------------------------------------------------------------

Query SupportTicket collection:

- by date range (from to) and fuzzy text over title and description fields:
    - method receives String searchTerm and optional parameters dateFrom and dateTo

All queries must be done db-side only, no backend filtering

https://www.mongodb.com/docs/drivers/java/sync/v4.3/fundamentals/crud/query-document/

**Comment by reactst** [comment]
u koje kontrolere sta da ubacin, napisa san querye

**Comment by bb00le** [comment]
Query za vozila na odredenoj udaljenosti od usera ubaci u vehicle controller
Query za tripove u trip controller
I query za support tickete u support ticket controller

Dodaj novi endpoint za svakoga mos ga bindat na /filter i neka primaju priko query parametara sve
