### ISSUE TITLE
Users CRUD

### ISSUE THREAD

**Issue by bb00le** [OSS-Java-Seminar-2022/BRK-Car-Sharing#7]
Create collection of User documents with properties:

Id (long, autogenerated)
Role (List<Role>, required)
DriverLicenseNum (int , required)
FirstName (String, required)
LastName (String, required)
Country (String, required)
City (String, required)
Adress (String, required)
PhoneNum(String, optional)
JoinDate(Date, required)
Subscription(Subscription, optional)

Create IUserRepository interface that extend MongoRepository<User, Long>

Create UserService with CRUD operations
 - GetUser
 - GetUsers
 - CreateUser
 - DeleteUser
 - DeleteUsers
 - UpdateUser

Create UserController with CRUD endpoints (top level route = "/api/user")
 - GetUser ( GET, /get )
 - GetUsers ( GET, /get )
 - CreateUser ( POST, /add )
 - DeleteUser ( DELETE, /delete )
 - DeleteUsers ( DELETE, /delete )
 - UpdateUser ( PATCH, /update )

**Comment by bb00le** [comment]
@karloresetar  nemoras radit poseban branch za ovo neka udje sa securityem sta radis

**Comment by karloresetar** [comment]
@bb00le jawohl!
